refactor: remove all other tests due to error
```
2023-01-15 08:56:28.262 xcodebuild[1411:29263] Writing error result bundle to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ResultBundle_2023-15-01_08-56-0028.xcresult
14
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
15
		{ platform:iOS Simulator, OS:12.4, name:iPhone X }
16

17
	The requested device could not be found because no available devices matched the request.
18

19
	Available destinations for the "EmojiPicker" scheme:
20
		{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:4203018E-580F-C1B5-9525-B745CECA79EB }
21
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
22
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
23
		{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
24
		{ platform:iOS Simulator, id:7B844DFB-ACB5-445F-9DCE-73F5F06A699C, OS:16.0, name:iPad (9th generation) }
25
		{ platform:iOS Simulator, id:4DEC9590-6005-4565-9477-2C0DF72BD012, OS:16.0, name:iPad Air (4th generation) }
26
		{ platform:iOS Simulator, id:8340A411-165E-4507-89F3-E6A1A2F641DA, OS:16.0, name:iPad Air (5th generation) }
27
		{ platform:iOS Simulator, id:40BC1E1F-2D7F-441C-8278-07E3F108881E, OS:16.0, name:iPad Pro (9.7-inch) }
28
		{ platform:iOS Simulator, id:E80EBC2D-2760-490E-9AF9-F8E1CC15AA17, OS:16.0, name:iPad Pro (11-inch) (3rd generation) }
29
		{ platform:iOS Simulator, id:B50C750F-83CE-4091-AA2D-FFC8D29A9E9B, OS:16.0, name:iPad Pro (12.9-inch) (5th generation) }
30
		{ platform:iOS Simulator, id:ABDFDC53-3EAC-4129-A463-7A9545371149, OS:16.0, name:iPad mini (6th generation) }
31
		{ platform:iOS Simulator, id:DB259A71-C861-4F5F-8C86-76C405AD45E4, OS:16.0, name:iPhone 8 }
32
		{ platform:iOS Simulator, id:61EB6313-8507-4567-82C5-DC1B6F371AA0, OS:16.0, name:iPhone 8 Plus }
33
		{ platform:iOS Simulator, id:31EF9535-E0F9-42B6-B216-B074C4C8F683, OS:16.0, name:iPhone 11 }
34
		{ platform:iOS Simulator, id:578EF79A-34A9-405C-A600-0B901BA4624D, OS:16.0, name:iPhone 11 Pro }
35
		{ platform:iOS Simulator, id:C5BCE86E-E6C0-4E64-AE49-005808F2918E, OS:16.0, name:iPhone 11 Pro Max }
36
		{ platform:iOS Simulator, id:63A63B15-4DBA-41CC-B2A4-373DE87483F2, OS:16.0, name:iPhone 12 }
37
		{ platform:iOS Simulator, id:109D2750-4DB7-4723-85A6-2F446F38CAE7, OS:16.0, name:iPhone 12 Pro }
38
		{ platform:iOS Simulator, id:C07FB95C-CDF1-485D-AB69-52AA17323958, OS:16.0, name:iPhone 12 Pro Max }
39
		{ platform:iOS Simulator, id:74A7A1DC-39F0-4DF9-920B-D37A10F8809F, OS:16.0, name:iPhone 12 mini }
40
		{ platform:iOS Simulator, id:C34176C6-5E17-4A67-846F-023FAA893238, OS:16.0, name:iPhone 13 }
41
		{ platform:iOS Simulator, id:D39E5CB7-108C-4F23-ACF3-C3AB576E160A, OS:16.0, name:iPhone 13 Pro }
42
		{ platform:iOS Simulator, id:7A2F0E11-F5D0-4939-B52B-3E47408C027E, OS:16.0, name:iPhone 13 Pro Max }
43
		{ platform:iOS Simulator, id:707D3B43-AA06-41C2-92A1-500A608C6525, OS:16.0, name:iPhone 13 mini }
44
		{ platform:iOS Simulator, id:E67DAAAB-AF35-4922-9CA6-04030A5566FA, OS:16.0, name:iPhone 14 }
45
		{ platform:iOS Simulator, id:BE0F9CD6-EF7B-4550-B098-AB47F8E58C95, OS:16.0, name:iPhone 14 Plus }
46
		{ platform:iOS Simulator, id:A2D88E3C-A916-4345-B20D-CF39E3F4D076, OS:16.0, name:iPhone 14 Pro }
47
		{ platform:iOS Simulator, id:F6D2C7E3-B6D4-464C-A931-33DC57689DA5, OS:16.0, name:iPhone 14 Pro Max }
48
		{ platform:iOS Simulator, id:DC572178-ED3D-4F57-9297-70D751A2797F, OS:16.0, name:iPhone SE (2nd generation) }
49
		{ platform:iOS Simulator, id:E7631040-2CCB-447E-8F39-120F8C714735, OS:16.0, name:iPhone SE (3rd generation) }
50
Error: Process completed with exit code 70.
```